### PR TITLE
Darpa subt

### PR DESCRIPTION
**Pull request by kubelvla**
Hi, consider this pull request, I've added an extra function declaration for processing a scan, which allows skipping the ICP step, keeping the prior. The motivation is to use the mapper as a good pointcloud assembler, with the filtering functions available.

### CODE REVIEW

**Comment by kubelvla** [comment]
Also, sorry for using this obsolete branch, I've started committing to it and realized that too late :confused:

**Comment by simonpierredeschenes** [comment]
Hi Vlad! Your changes look good, but the darpa branch contains stuff that should not get to the master branch. I'll try to create a new pull request with just your changes and then we will be able to merge it.

**Comment by kubelvla** [comment]
Ah, those changes to make it catkin_isolated-buildable. The master doesn't have it, does it @simonpierredeschenes? I'd like to retain that functionality though. I'll stay on the darpa branch then and will keep pulling master in. You can consider adding my changes, they are for the pointcloud assembler branch in the _ros repository. But I guess it's useful mainly for me, so don't worry, I'm canceling this pull req.

**Comment by simonpierredeschenes** [comment]
Thanks for the pull request anyway, it's definitely a good idea to add the possibility to skip the ICP. I'll add it to the master branch eventually. If you need anything, I will be glad to help!

**Pull request closed without merging**
